# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Messinese Gianluca's website
email: gianluca.messi1@gmail.com					
description: > # this means to ignore newlines until "baseurl:"
  Messinese Gianluca, computer science italian student from Barletta. 
baseurl: /
url: "https://messinesegianluca.github.io" # the base hostname & protocol for your site
github_username:  MessineseGianluca

# Build settings
markdown: kramdown
permalink: pretty